### PR TITLE
typo refine locale-en-us.json

### PR DESCRIPTION
**Pull request by san-tak**
I'm making locale "ja-jp" now; (working branch : "san-tak/features/locale-ja-jp/")
During translation working, I found some typo words in the "en-us" file.

### CODE REVIEW

**Comment by lucboutier** [comment]
Hi!
Thanks for that, and great news to have a jp locale!
I have to edit your pull-request before I merge it as I would like to change 
+        "INPUTS": "Entry into artifacts",
into 
+        "INPUTS": "Input artifacts",

I will do that later today or early tomorrow.

Luc

**Comment by san-tak** [comment]
I was confirmed your fix. then  I'd like to  merge my repository from upstream.

Thanks;

**Comment by lucboutier** [comment]
Hi,

As you may have seen we have been doing quite a big refactoring this week. Our goal was to allow users to create plugins that will bring their own UI and REST services (we still have a little work there to change Spring security configuration to be fully annotation based).

Anyway all the ui related files are now placed in alien4cloud-ui/src/main/webapp/ so are the translation files.

Sorry for the impacts it may have on your work.

Luc

**Comment by san-tak** [comment]
Hi,

Yes, I have seen your refactoring HARD work. :smile:
I think really exciting things your "implementation of the allow users to create plugins".

Have a nice weekend!

**Pull request closed without merging**
